baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Dummy site (Relearn)'
theme = 'Relearn'
[taxonomies]
  category = 'categories'
  tag = 'tags'
[params]
  date_format = '2006-01-02' # Example format
