baseURL = 'https://kite-kuma.github.io/dummy_website/'
languageCode = 'en-us'
title = 'Dummy site'
theme = 'PaperMod'
[taxonomies]
  category = 'categories'
  tag = 'tags'
[params]
  date_format = '2006-01-02' # Example format
